language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "iojs"
before_install:
  - npm i -g npm@^2.0.0
before_success:
  - npm run test
after_success:
  - npm run semantic-release
